### ISSUE TITLE
`play_from` doesn't seem to play queued songs

### ISSUE THREAD

**Issue by antoniouaa** [antoniouaa/spotify_bot#12]
Loading a playlist into the queue does not seem to have the bot play the songs in sequence.

`play_from alex newrock` loaded 17 songs
The second song in the queue never started playing, I had to force it by using `skip`

**Comment by erikoui** [comment]
Trying a fix which involves using a single asyncio event loop instead of two, in music.py

**Comment by erikoui** [comment]
Fixed, see pr

**Comment by antoniouaa** [comment]
Pog.
